import{r as e}from"./assets/rolldown-runtime-hePW80VL.js";import{a as t,i as n,n as r,r as i,t as a}from"./assets/vendor-DD-Ufsy1.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),t.credentials=e.crossOrigin===`use-credentials`?`include`:e.crossOrigin===`anonymous`?`omit`:`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var o=document.getElementById(`mobileMenu`),s=document.getElementById(`mobileMenuClose`),c=o.querySelectorAll(`a[href^='#'], a[data-scroll-top]`),l=768;function u(){o.classList.add(`is-open`),document.body.classList.add(`no-scroll`);let e=document.getElementById(`hamburger`);e&&e.setAttribute(`aria-expanded`,`true`),s.focus()}function d(){o.classList.remove(`is-open`),document.body.classList.remove(`no-scroll`);let e=document.getElementById(`hamburger`);e&&(e.setAttribute(`aria-expanded`,`false`),e.focus())}function f(){return o.classList.contains(`is-open`)}document.addEventListener(`click`,e=>{e.target.closest(`#hamburger`)&&(f()?d():u())}),s.addEventListener(`click`,d),document.addEventListener(`keydown`,e=>{e.key===`Escape`&&f()&&d()}),c.forEach(e=>{e.addEventListener(`click`,()=>{f()&&d()})}),o.querySelectorAll(`a[href^='#']:not([data-scroll-top])`).forEach(e=>{let t=e.getAttribute(`href`);t===`#`||t.length<=1||e.addEventListener(`click`,e=>{let n=document.querySelector(t);n&&(e.preventDefault(),n.scrollIntoView({behavior:`smooth`,block:`start`}))})}),o.querySelectorAll(`[data-scroll-top]`).forEach(e=>{e.addEventListener(`click`,e=>{e.preventDefault(),window.scrollTo({top:0,behavior:`smooth`}),d()})}),window.addEventListener(`resize`,()=>{window.innerWidth>=l&&f()&&d()});function p(){document.querySelector(`.global-loader-overlay`).classList.remove(`hidden`)}function m(){document.querySelector(`.global-loader-overlay`).classList.add(`hidden`)}var h=`https://deserts-store.b.goit.study/api/`;async function g({method:e=`get`,body:n={},route:r=``}){p();let i=h+r,a={};return e.toLowerCase()===`get`?a=await t.get(i,{params:n}):e.toLowerCase()===`post`&&(a=await t.post(i,n)),m(),a}var _=e(n(),1),v=`/sweet_workshop/assets/icons-Cqnh3VUO.svg`,y=document.querySelector(`.dessert-filter`),b=document.querySelector(`.dessert-filter-select`),x=document.querySelector(`.dessert-select-trigger`),S=document.querySelector(`.dessert-select-title`),C=document.querySelector(`.dessert-custom-options`),w=document.querySelector(`.dessert-list`),T=document.querySelector(`.load-more`),E=`all`,D=1;y.innerHTML=`
    <label class="dessert-category-label">
        <input class="dessert-btn" type="radio" name="dessert-category" value="all" checked>
        <span class="dessert-name">Всі десерти</span>
    </label>
`,b.innerHTML=`
    <option class="select-item active" value="all">Всі десерти</option>
`,C.innerHTML=`
    <li class="custom-option active" data-value="all"><span>Всі десерти</span>  </li>
`;async function O(){try{let e=(await g({method:`get`,route:`categories`})).data;y.insertAdjacentHTML(`beforeend`,k(e)),b.insertAdjacentHTML(`beforeend`,A(e)),C.insertAdjacentHTML(`beforeend`,j(e))}catch{_.default.error({title:`Увага`,titleSize:`16`,message:`Помилка завантаження категорій`,messageSize:`16`,position:`topRight`,timeout:5e3})}}function k(e){return e.map(({_id:e,name:t})=>`
        <label class="dessert-category-label">
            <input class="dessert-btn" type="radio" name="dessert-category" value="${e}">
            <span class="dessert-name">${t}</span>
        </label>    
    `).join(``)}function A(e){return e.map(({_id:e,name:t})=>`
        <option class="select-item" value="${e}">${t}</option>
    `).join(``)}function j(e){return e.map(({_id:e,name:t})=>`
        <li class="custom-option" data-value="${e}"><span>${t}</span></li>
    `).join(``)}O();function M(){D=1,w.innerHTML=``,N()}async function N(){try{let e={page:D,limit:8};E!==`all`&&(e.category=E);let t=await g({method:`get`,body:e,route:`desserts`}),n=t.data.desserts;return w.insertAdjacentHTML(`beforeend`,P(n)),w.children.length>=t.data.totalItems||n.length<8?T.style.display=`none`:T.style.display=`block`,n}catch{return _.default.error({title:`Увага`,titleSize:`16`,message:`Помилка завантаження десертів`,messageSize:`16`,position:`topRight`,timeout:5e3}),T.style.display=`block`,[]}}function P(e){return e.map(({_id:e,category:{name:t},description:n,image:r,name:i,price:a})=>`
        <li class="card-item" data-id="${e}">
            <img class="card-img" src="${r}" alt="${i}" />
            <p class="card-category"> ${t}</p>
            <h3 class="card-name"> ${i}</h3>
            <p class="card-descr"> ${n}</p>
            <div class="card-footer">
                <p class="card-price"><span class="price-value">${a}</span>грн</p>
                <button class="card-btn" type="button">
                    <svg width="24" height="24">
                        <use href="${v}#icon-arrow_outward"></use>
                    </svg>
                </button>
            </div>         
        </li>
    `).join(``)}N();function F(){if(E===`all`)return`десерти`;let e=C.querySelector(`[data-value="${E}"]`);if(e)return e.textContent.trim().toLowerCase()}T.addEventListener(`click`,async()=>{if(D+=1,T.style.display=`none`,(await N()).length<8){let e=F();_.default.warning({title:`Увага`,titleSize:`16`,message:`Ви завантажили всі ${e}`,messageSize:`16`,position:`topRight`,timeout:5e3})}}),b.addEventListener(`change`,e=>{E=e.target.value;let t=y.querySelector(`input[value="${E}"]`);t&&(t.checked=!0);let n=C.querySelector(`[data-value="${E}"]`);n&&(S.textContent=n.textContent,C.querySelectorAll(`.custom-option`).forEach(e=>e.classList.remove(`active`)),n.classList.add(`active`)),M()}),y.addEventListener(`change`,e=>{if(e.target.classList.contains(`dessert-btn`)){E=e.target.value,b.value=E;let t=C.querySelector(`[data-value="${E}"]`);t&&(S.textContent=t.textContent,C.querySelectorAll(`.custom-option`).forEach(e=>e.classList.remove(`active`)),t.classList.add(`active`)),M()}}),x.addEventListener(`click`,e=>{e.stopPropagation(),C.classList.toggle(`visually-hidden`),x.classList.toggle(`is-open`)}),C.addEventListener(`click`,e=>{let t=e.target.closest(`.custom-option`);if(!t)return;E=t.dataset.value,S.textContent=t.textContent,C.querySelectorAll(`.custom-option`).forEach(e=>e.classList.remove(`active`)),t.classList.add(`active`),b.value=E;let n=y.querySelector(`input[value="${E}"]`);n&&(n.checked=!0),M(),C.classList.add(`visually-hidden`)}),document.addEventListener(`click`,()=>{C.classList.add(`visually-hidden`),x.classList.remove(`is-open`)});var I=null;function L(){window.innerWidth>=768&&!I&&(I=new i(`.aboutSwiper`,{modules:[r,a],slidesPerView:2,spaceBetween:24,loop:!1,pagination:{el:`.about-pagination`,clickable:!0},navigation:{nextEl:`.about-button-next`,prevEl:`.about-button-prev`}})),window.innerWidth<768&&I&&(I.destroy(!0,!0),I=null)}L(),window.addEventListener(`resize`,L);
//# sourceMappingURL=index.js.map