import{r as e}from"./assets/rolldown-runtime-hePW80VL.js";import{n as t,t as n}from"./assets/vendor-DLaoNbSX.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),t.credentials=e.crossOrigin===`use-credentials`?`include`:e.crossOrigin===`anonymous`?`omit`:`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var r=document.getElementById(`mobileMenu`),i=document.getElementById(`mobileMenuClose`),a=r.querySelectorAll(`a[href^='#'], a[data-scroll-top]`),o=768;function s(){r.classList.add(`is-open`),document.body.classList.add(`no-scroll`);let e=document.getElementById(`hamburger`);e&&e.setAttribute(`aria-expanded`,`true`),i.focus()}function c(){r.classList.remove(`is-open`),document.body.classList.remove(`no-scroll`);let e=document.getElementById(`hamburger`);e&&(e.setAttribute(`aria-expanded`,`false`),e.focus())}function l(){return r.classList.contains(`is-open`)}document.addEventListener(`click`,e=>{e.target.closest(`#hamburger`)&&(l()?c():s())}),i.addEventListener(`click`,c),document.addEventListener(`keydown`,e=>{e.key===`Escape`&&l()&&c()}),a.forEach(e=>{e.addEventListener(`click`,()=>{l()&&c()})}),r.querySelectorAll(`a[href^='#']:not([data-scroll-top])`).forEach(e=>{let t=e.getAttribute(`href`);t===`#`||t.length<=1||e.addEventListener(`click`,e=>{let n=document.querySelector(t);n&&(e.preventDefault(),n.scrollIntoView({behavior:`smooth`,block:`start`}))})}),r.querySelectorAll(`[data-scroll-top]`).forEach(e=>{e.addEventListener(`click`,e=>{e.preventDefault(),window.scrollTo({top:0,behavior:`smooth`}),c()})}),window.addEventListener(`resize`,()=>{window.innerWidth>=o&&l()&&c()});function u(){document.querySelector(`.global-loader-overlay`).classList.remove(`hidden`)}function d(){document.querySelector(`.global-loader-overlay`).classList.add(`hidden`)}var f=`https://deserts-store.b.goit.study/api/`;async function p({method:e=`get`,body:n={},route:r=``}){u();let i=f+r,a={};return e.toLowerCase()===`get`?a=await t.get(i,{params:n}):e.toLowerCase()===`post`&&(a=await t.post(i,n)),d(),a}var m=e(n(),1),h=`/sweet_workshop/assets/icons-Cqnh3VUO.svg`,g=document.querySelector(`.dessert-filter`),_=document.querySelector(`.dessert-filter-select`),v=document.querySelector(`.dessert-select-trigger`),y=document.querySelector(`.dessert-select-title`),b=document.querySelector(`.dessert-custom-options`),x=document.querySelector(`.dessert-list`),S=document.querySelector(`.load-more`),C=`all`,w=1;g.innerHTML=`
    <label class="dessert-category-label">
        <input class="dessert-btn" type="radio" name="dessert-category" value="all" checked>
        <span class="dessert-name">Всі десерти</span>
    </label>
`,_.innerHTML=`
    <option class="select-item active" value="all">Всі десерти</option>
`,b.innerHTML=`
    <li class="custom-option active" data-value="all"><span>Всі десерти</span>  </li>
`;async function T(){try{let e=(await p({method:`get`,route:`categories`})).data;g.insertAdjacentHTML(`beforeend`,E(e)),_.insertAdjacentHTML(`beforeend`,D(e)),b.insertAdjacentHTML(`beforeend`,O(e))}catch{m.default.error({title:`Увага`,titleSize:`16`,message:`Помилка завантаження категорій`,messageSize:`16`,position:`topRight`,timeout:5e3})}}function E(e){return e.map(({_id:e,name:t})=>`
        <label class="dessert-category-label">
            <input class="dessert-btn" type="radio" name="dessert-category" value="${e}">
            <span class="dessert-name">${t}</span>
        </label>    
    `).join(``)}function D(e){return e.map(({_id:e,name:t})=>`
        <option class="select-item" value="${e}">${t}</option>
    `).join(``)}function O(e){return e.map(({_id:e,name:t})=>`
        <li class="custom-option" data-value="${e}"><span>${t}</span></li>
    `).join(``)}T();function k(){w=1,x.innerHTML=``,A()}async function A(){try{let e={page:w,limit:8};C!==`all`&&(e.category=C);let t=await p({method:`get`,body:e,route:`desserts`}),n=t.data.desserts;return x.insertAdjacentHTML(`beforeend`,j(n)),x.children.length>=t.data.totalItems||n.length<8?S.style.display=`none`:S.style.display=`block`,n}catch{return m.default.error({title:`Увага`,titleSize:`16`,message:`Помилка завантаження десертів`,messageSize:`16`,position:`topRight`,timeout:5e3}),S.style.display=`block`,[]}}function j(e){return e.map(({_id:e,category:{name:t},description:n,image:r,name:i,price:a})=>`
        <li class="card-item" data-id="${e}">
            <img class="card-img" src="${r}" alt="${i}" />
            <p class="card-category"> ${t}</p>
            <h3 class="card-name"> ${i}</h3>
            <p class="card-descr"> ${n}</p>
            <div class="card-footer">
                <p class="card-price"><span class="price-value">${a}</span>грн</p>
                <button class="card-btn" type="button">
                    <svg width="24" height="24">
                        <use href="${h}#icon-arrow_outward"></use>
                    </svg>
                </button>
            </div>         
        </li>
    `).join(``)}A();function M(){if(C===`all`)return`десерти`;let e=b.querySelector(`[data-value="${C}"]`);if(e)return e.textContent.trim().toLowerCase()}S.addEventListener(`click`,async()=>{if(w+=1,S.style.display=`none`,(await A()).length<8){let e=M();m.default.warning({title:`Увага`,titleSize:`16`,message:`Ви завантажили всі ${e}`,messageSize:`16`,position:`topRight`,timeout:5e3})}}),_.addEventListener(`change`,e=>{C=e.target.value;let t=g.querySelector(`input[value="${C}"]`);t&&(t.checked=!0);let n=b.querySelector(`[data-value="${C}"]`);n&&(y.textContent=n.textContent,b.querySelectorAll(`.custom-option`).forEach(e=>e.classList.remove(`active`)),n.classList.add(`active`)),k()}),g.addEventListener(`change`,e=>{if(e.target.classList.contains(`dessert-btn`)){C=e.target.value,_.value=C;let t=b.querySelector(`[data-value="${C}"]`);t&&(y.textContent=t.textContent,b.querySelectorAll(`.custom-option`).forEach(e=>e.classList.remove(`active`)),t.classList.add(`active`)),k()}}),v.addEventListener(`click`,e=>{e.stopPropagation(),b.classList.toggle(`visually-hidden`),v.classList.toggle(`is-open`)}),b.addEventListener(`click`,e=>{let t=e.target.closest(`.custom-option`);if(!t)return;C=t.dataset.value,y.textContent=t.textContent,b.querySelectorAll(`.custom-option`).forEach(e=>e.classList.remove(`active`)),t.classList.add(`active`),_.value=C;let n=g.querySelector(`input[value="${C}"]`);n&&(n.checked=!0),k(),b.classList.add(`visually-hidden`)}),document.addEventListener(`click`,()=>{b.classList.add(`visually-hidden`),v.classList.remove(`is-open`)});
//# sourceMappingURL=index.js.map